//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem.BankSystemService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/BankSystemService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardsView", Namespace="http://schemas.datacontract.org/2004/07/BankSystemService")]
    [System.SerializableAttribute()]
    public partial class CardsView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableField, value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.BalanceField, value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((this.CardNumberField.Equals(value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionsView", Namespace="http://schemas.datacontract.org/2004/07/BankSystemService")]
    [System.SerializableAttribute()]
    public partial class TransactionsView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.BalanceField, value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionsUsersCardsView", Namespace="http://schemas.datacontract.org/2004/07/BankSystemService")]
    [System.SerializableAttribute()]
    public partial class TransactionsUsersCardsView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardAvailable {
            get {
                return this.CardAvailableField;
            }
            set {
                if ((object.ReferenceEquals(this.CardAvailableField, value) != true)) {
                    this.CardAvailableField = value;
                    this.RaisePropertyChanged("CardAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardBalance {
            get {
                return this.CardBalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.CardBalanceField, value) != true)) {
                    this.CardBalanceField = value;
                    this.RaisePropertyChanged("CardBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((this.CardIdField.Equals(value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((this.CardNumberField.Equals(value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionAmount {
            get {
                return this.TransactionAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionAmountField, value) != true)) {
                    this.TransactionAmountField = value;
                    this.RaisePropertyChanged("TransactionAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionBalance {
            get {
                return this.TransactionBalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionBalanceField, value) != true)) {
                    this.TransactionBalanceField = value;
                    this.RaisePropertyChanged("TransactionBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((this.TransactionIdField.Equals(value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCardsView", Namespace="http://schemas.datacontract.org/2004/07/BankSystemService")]
    [System.SerializableAttribute()]
    public partial class UserCardsView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableField, value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.BalanceField, value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((this.CardIdField.Equals(value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((this.CardNumberField.Equals(value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankSystemService.IBankSystemService")]
    public interface IBankSystemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetData", ReplyAction="http://tempuri.org/IBankSystemService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetData", ReplyAction="http://tempuri.org/IBankSystemService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IBankSystemService/GetDataUsingDataContractResponse")]
        BankSystem.BankSystemService.CompositeType GetDataUsingDataContract(BankSystem.BankSystemService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IBankSystemService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BankSystem.BankSystemService.CompositeType> GetDataUsingDataContractAsync(BankSystem.BankSystemService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetCards", ReplyAction="http://tempuri.org/IBankSystemService/GetCardsResponse")]
        BankSystem.BankSystemService.CardsView[] GetCards(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetCards", ReplyAction="http://tempuri.org/IBankSystemService/GetCardsResponse")]
        System.Threading.Tasks.Task<BankSystem.BankSystemService.CardsView[]> GetCardsAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetCardsWithoutUser", ReplyAction="http://tempuri.org/IBankSystemService/GetCardsWithoutUserResponse")]
        BankSystem.BankSystemService.CardsView[] GetCardsWithoutUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetCardsWithoutUser", ReplyAction="http://tempuri.org/IBankSystemService/GetCardsWithoutUserResponse")]
        System.Threading.Tasks.Task<BankSystem.BankSystemService.CardsView[]> GetCardsWithoutUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/AddCard", ReplyAction="http://tempuri.org/IBankSystemService/AddCardResponse")]
        System.Web.Security.MembershipCreateStatus AddCard(string id, string nazwa, ulong nrKarta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/AddCard", ReplyAction="http://tempuri.org/IBankSystemService/AddCardResponse")]
        System.Threading.Tasks.Task<System.Web.Security.MembershipCreateStatus> AddCardAsync(string id, string nazwa, ulong nrKarta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/AddNewCard", ReplyAction="http://tempuri.org/IBankSystemService/AddNewCardResponse")]
        System.Web.Security.MembershipCreateStatus AddNewCard(ulong nrCard, float srodki, float saldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/AddNewCard", ReplyAction="http://tempuri.org/IBankSystemService/AddNewCardResponse")]
        System.Threading.Tasks.Task<System.Web.Security.MembershipCreateStatus> AddNewCardAsync(ulong nrCard, float srodki, float saldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/CreateTransaktion", ReplyAction="http://tempuri.org/IBankSystemService/CreateTransaktionResponse")]
        System.Web.Security.MembershipCreateStatus CreateTransaktion(string userId, System.Nullable<System.DateTime> data, string tytul, float kwota, float saldo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/CreateTransaktion", ReplyAction="http://tempuri.org/IBankSystemService/CreateTransaktionResponse")]
        System.Threading.Tasks.Task<System.Web.Security.MembershipCreateStatus> CreateTransaktionAsync(string userId, System.Nullable<System.DateTime> data, string tytul, float kwota, float saldo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/CreateFullTransaktion", ReplyAction="http://tempuri.org/IBankSystemService/CreateFullTransaktionResponse")]
        System.Web.Security.MembershipCreateStatus CreateFullTransaktion(string userId, System.Nullable<System.DateTime> data, string tytul, ulong nrCard, string name, string miejscowosc, string ulica, string kod, float kwota, float saldo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/CreateFullTransaktion", ReplyAction="http://tempuri.org/IBankSystemService/CreateFullTransaktionResponse")]
        System.Threading.Tasks.Task<System.Web.Security.MembershipCreateStatus> CreateFullTransaktionAsync(string userId, System.Nullable<System.DateTime> data, string tytul, ulong nrCard, string name, string miejscowosc, string ulica, string kod, float kwota, float saldo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetSaldoByCardName", ReplyAction="http://tempuri.org/IBankSystemService/GetSaldoByCardNameResponse")]
        float GetSaldoByCardName(string nazwa, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetSaldoByCardName", ReplyAction="http://tempuri.org/IBankSystemService/GetSaldoByCardNameResponse")]
        System.Threading.Tasks.Task<float> GetSaldoByCardNameAsync(string nazwa, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetIdByCardName", ReplyAction="http://tempuri.org/IBankSystemService/GetIdByCardNameResponse")]
        int GetIdByCardName(string nazwa, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetIdByCardName", ReplyAction="http://tempuri.org/IBankSystemService/GetIdByCardNameResponse")]
        System.Threading.Tasks.Task<int> GetIdByCardNameAsync(string nazwa, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetTransaktionsByUserId", ReplyAction="http://tempuri.org/IBankSystemService/GetTransaktionsByUserIdResponse")]
        BankSystem.BankSystemService.TransactionsView[] GetTransaktionsByUserId(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetTransaktionsByUserId", ReplyAction="http://tempuri.org/IBankSystemService/GetTransaktionsByUserIdResponse")]
        System.Threading.Tasks.Task<BankSystem.BankSystemService.TransactionsView[]> GetTransaktionsByUserIdAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetTransaktionsByNrCard", ReplyAction="http://tempuri.org/IBankSystemService/GetTransaktionsByNrCardResponse")]
        BankSystem.BankSystemService.TransactionsUsersCardsView[] GetTransaktionsByNrCard(ulong nrCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetTransaktionsByNrCard", ReplyAction="http://tempuri.org/IBankSystemService/GetTransaktionsByNrCardResponse")]
        System.Threading.Tasks.Task<BankSystem.BankSystemService.TransactionsUsersCardsView[]> GetTransaktionsByNrCardAsync(ulong nrCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetExistingCard", ReplyAction="http://tempuri.org/IBankSystemService/GetExistingCardResponse")]
        void GetExistingCard(ulong nrCard, float kwota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetExistingCard", ReplyAction="http://tempuri.org/IBankSystemService/GetExistingCardResponse")]
        System.Threading.Tasks.Task GetExistingCardAsync(ulong nrCard, float kwota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetCardsByAdmin", ReplyAction="http://tempuri.org/IBankSystemService/GetCardsByAdminResponse")]
        BankSystem.BankSystemService.UserCardsView[] GetCardsByAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankSystemService/GetCardsByAdmin", ReplyAction="http://tempuri.org/IBankSystemService/GetCardsByAdminResponse")]
        System.Threading.Tasks.Task<BankSystem.BankSystemService.UserCardsView[]> GetCardsByAdminAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankSystemServiceChannel : BankSystem.BankSystemService.IBankSystemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankSystemServiceClient : System.ServiceModel.ClientBase<BankSystem.BankSystemService.IBankSystemService>, BankSystem.BankSystemService.IBankSystemService {
        
        public BankSystemServiceClient() {
        }
        
        public BankSystemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankSystemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankSystemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankSystemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public BankSystem.BankSystemService.CompositeType GetDataUsingDataContract(BankSystem.BankSystemService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<BankSystem.BankSystemService.CompositeType> GetDataUsingDataContractAsync(BankSystem.BankSystemService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public BankSystem.BankSystemService.CardsView[] GetCards(string id) {
            return base.Channel.GetCards(id);
        }
        
        public System.Threading.Tasks.Task<BankSystem.BankSystemService.CardsView[]> GetCardsAsync(string id) {
            return base.Channel.GetCardsAsync(id);
        }
        
        public BankSystem.BankSystemService.CardsView[] GetCardsWithoutUser() {
            return base.Channel.GetCardsWithoutUser();
        }
        
        public System.Threading.Tasks.Task<BankSystem.BankSystemService.CardsView[]> GetCardsWithoutUserAsync() {
            return base.Channel.GetCardsWithoutUserAsync();
        }
        
        public System.Web.Security.MembershipCreateStatus AddCard(string id, string nazwa, ulong nrKarta) {
            return base.Channel.AddCard(id, nazwa, nrKarta);
        }
        
        public System.Threading.Tasks.Task<System.Web.Security.MembershipCreateStatus> AddCardAsync(string id, string nazwa, ulong nrKarta) {
            return base.Channel.AddCardAsync(id, nazwa, nrKarta);
        }
        
        public System.Web.Security.MembershipCreateStatus AddNewCard(ulong nrCard, float srodki, float saldo) {
            return base.Channel.AddNewCard(nrCard, srodki, saldo);
        }
        
        public System.Threading.Tasks.Task<System.Web.Security.MembershipCreateStatus> AddNewCardAsync(ulong nrCard, float srodki, float saldo) {
            return base.Channel.AddNewCardAsync(nrCard, srodki, saldo);
        }
        
        public System.Web.Security.MembershipCreateStatus CreateTransaktion(string userId, System.Nullable<System.DateTime> data, string tytul, float kwota, float saldo, int id) {
            return base.Channel.CreateTransaktion(userId, data, tytul, kwota, saldo, id);
        }
        
        public System.Threading.Tasks.Task<System.Web.Security.MembershipCreateStatus> CreateTransaktionAsync(string userId, System.Nullable<System.DateTime> data, string tytul, float kwota, float saldo, int id) {
            return base.Channel.CreateTransaktionAsync(userId, data, tytul, kwota, saldo, id);
        }
        
        public System.Web.Security.MembershipCreateStatus CreateFullTransaktion(string userId, System.Nullable<System.DateTime> data, string tytul, ulong nrCard, string name, string miejscowosc, string ulica, string kod, float kwota, float saldo, int id) {
            return base.Channel.CreateFullTransaktion(userId, data, tytul, nrCard, name, miejscowosc, ulica, kod, kwota, saldo, id);
        }
        
        public System.Threading.Tasks.Task<System.Web.Security.MembershipCreateStatus> CreateFullTransaktionAsync(string userId, System.Nullable<System.DateTime> data, string tytul, ulong nrCard, string name, string miejscowosc, string ulica, string kod, float kwota, float saldo, int id) {
            return base.Channel.CreateFullTransaktionAsync(userId, data, tytul, nrCard, name, miejscowosc, ulica, kod, kwota, saldo, id);
        }
        
        public float GetSaldoByCardName(string nazwa, string userId) {
            return base.Channel.GetSaldoByCardName(nazwa, userId);
        }
        
        public System.Threading.Tasks.Task<float> GetSaldoByCardNameAsync(string nazwa, string userId) {
            return base.Channel.GetSaldoByCardNameAsync(nazwa, userId);
        }
        
        public int GetIdByCardName(string nazwa, string userId) {
            return base.Channel.GetIdByCardName(nazwa, userId);
        }
        
        public System.Threading.Tasks.Task<int> GetIdByCardNameAsync(string nazwa, string userId) {
            return base.Channel.GetIdByCardNameAsync(nazwa, userId);
        }
        
        public BankSystem.BankSystemService.TransactionsView[] GetTransaktionsByUserId(string userId) {
            return base.Channel.GetTransaktionsByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<BankSystem.BankSystemService.TransactionsView[]> GetTransaktionsByUserIdAsync(string userId) {
            return base.Channel.GetTransaktionsByUserIdAsync(userId);
        }
        
        public BankSystem.BankSystemService.TransactionsUsersCardsView[] GetTransaktionsByNrCard(ulong nrCard) {
            return base.Channel.GetTransaktionsByNrCard(nrCard);
        }
        
        public System.Threading.Tasks.Task<BankSystem.BankSystemService.TransactionsUsersCardsView[]> GetTransaktionsByNrCardAsync(ulong nrCard) {
            return base.Channel.GetTransaktionsByNrCardAsync(nrCard);
        }
        
        public void GetExistingCard(ulong nrCard, float kwota) {
            base.Channel.GetExistingCard(nrCard, kwota);
        }
        
        public System.Threading.Tasks.Task GetExistingCardAsync(ulong nrCard, float kwota) {
            return base.Channel.GetExistingCardAsync(nrCard, kwota);
        }
        
        public BankSystem.BankSystemService.UserCardsView[] GetCardsByAdmin() {
            return base.Channel.GetCardsByAdmin();
        }
        
        public System.Threading.Tasks.Task<BankSystem.BankSystemService.UserCardsView[]> GetCardsByAdminAsync() {
            return base.Channel.GetCardsByAdminAsync();
        }
    }
}
