//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystemService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardsView
    {
        public int Id { get; set; }
        public long CardNumber { get; set; }
        public string Available { get; set; }
        public string Balance { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
    }
}
