//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystemService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsUsersCardsView
    {
        public int TransactionId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Title { get; set; }
        public string TransactionAmount { get; set; }
        public string TransactionBalance { get; set; }
        public string UserName { get; set; }
        public int CardId { get; set; }
        public long CardNumber { get; set; }
        public string CardAvailable { get; set; }
        public string CardBalance { get; set; }
        public string CardName { get; set; }
    }
}
