//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystemService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCardsView
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CardId { get; set; }
        public long CardNumber { get; set; }
        public string Available { get; set; }
        public string Balance { get; set; }
        public string CardName { get; set; }
    }
}
